# PostgreSQL. Versions 8.2 and up are supported.
#
development:
  adapter: postgresql
  encoding: unicode
  database: doubledate
  pool: 10
  username: michael
  password:
  
test:
  adapter: postgresql
  encoding: unicode
  database: doubledate_test
  pool: 5
  username: michael
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: doubledate_staging
  host: localhost
  password: "never fly without your wings"
  allow_concurrency: true
  port: 5432
  pool: 10

linode: &linode
  adapter: postgresql
  encoding: unicode
  host: blitzen
  database: doubledate 
  username: doubledate
  password: "never fly without your wings"
  allow_concurrency: true
  port: 5432
  pool: 30

production:
  <<: *linode
