# examples
# UserFeature(cost: 50, family: num_dates, level: 1, slug: post_5_dates)
# UserFeature(cost: 50, family: num_dates, level: 2, slug: post_10_dates)

max_activities:
  post_3_activities:
    level: 0
    cost: 0
    value: 3
  post_5_activities:
    level: 1
    cost: 50
    value: 5
  post_10_activities:
    level: 2
    cost: 50
    value: 10